# Lab | Data Structuring and Combining Data

##### Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [1]:
import pandas as pd

In [2]:
df1 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
df1.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323

In [3]:
df2 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")
df2.head()

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Total Claim Amount,Policy Type,Vehicle Class
0,GS98873,Arizona,F,Bachelor,323912.47%,16061,88,1/0/00,633.6,Personal Auto,Four-Door Car
1,CW49887,California,F,Master,462680.11%,79487,114,1/0/00,547.2,Special Auto,SUV
2,MY31220,California,F,College,899704.02%,54230,112,1/0/00,537.6,Personal Auto,Two-Door Car
3,UH35128,Oregon,F,College,2580706.30%,71210,214,1/1/00,1027.2,Personal Auto,Luxury Car
4,WH52799,Arizona,F,College,380812.21%,94903,94,1/0/00,451.2,Corporate Auto,Two-Door Car

In [4]:
df3= pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")
df3.head()

,Customer,State,Customer Lifetime Value,Education,Gender,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Total Claim Amount,Vehicle Class
0,SA25987,Washington,3479.137523,High School or Below,M,0,104,0,Personal Auto,499.200000,Two-Door Car
1,TB86706,Arizona,2502.637401,Master,M,0,66,0,Personal Auto,3.468912,Two-Door Car
2,ZL73902,Nevada,3265.156348,Bachelor,F,25820,82,0,Personal Auto,393.600000,Four-Door Car
3,KX23516,California,4455.843406,High School or Below,F,0,121,0,Personal Auto,699.615192,SUV
4,FN77294,California,7704.958480,High School or Below,M,30366,101,2,Personal Auto,484.800000,SUV

In [5]:
df1.columns = df1.columns.str.lower().str.strip()
df2.columns = df2.columns.str.lower().str.strip()
df3.columns = df3.columns.str.lower().str.strip()


df1 = df1.rename(columns={'st': 'state', 'gender': 'gender'}) 
df2 = df2.rename(columns={'st': 'state', 'gender': 'gender'})
df3 = df3.rename(columns={'st': 'state', 'gender': 'gender'})

In [6]:
df = pd.concat([df1, df2, df3], axis=0, ignore_index=True)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9015 non-null   object
 3   education                  9137 non-null   object
 4   customer lifetime value    9130 non-null   object
 5   income                     9137 non-null   float64
 6   monthly premium auto       9137 non-null   float64
 7   number of open complaints  9137 non-null   object
 8   policy type                9137 non-null   object
 9   vehicle class              9137 non-null   object
 10  total claim amount         9137 non-null   float64
dtypes: float64(3), object(8)
memory usage: 1.0+ MB

In [8]:
df.rename(columns={col : col.replace(" ", "_").lower() for col in df.columns}, inplace = True)

In [9]:
gender_map = {
    'f': 'F', 'female': 'F', 'femal': 'F',
    'm': 'M', 'male': 'M',
}

df['gender'] = df['gender'].replace(gender_map)

In [10]:
state_rep = {
    "AZ": "Arizona", "Cali": "California", "WA": "Washington"
}

df['state'] = df['state'].replace(state_rep)
df.head(10)

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323
5,OC83172,Oregon,F,Bachelor,825629.78%,62902.0,69.0,1/0/00,Personal Auto,Two-Door Car,159.383042
6,XZ87318,Oregon,F,College,538089.86%,55350.0,67.0,1/0/00,Corporate Auto,Four-Door Car,321.600000
7,CF85061,Arizona,M,Master,721610.03%,0.0,101.0,1/0/00,Corporate Auto,Four-Door Car,363.029680
8,DY87989,Oregon,M,Bachelor,2412750.40%,14072.0,71.0,1/0/00,Corporate Auto,Four-Door Car,511.200000
9,BQ94931,Oregon,F,College,738817.81%,28812.0,93.0,1/0/00,Special Auto,Four-Door Car,425.527834

In [11]:
df["customer_lifetime_value"] = df["customer_lifetime_value"].apply(lambda x: float(str(x).replace('%', '')) if pd.notnull(x) else x)

In [12]:
complaints_ = {
    "1/0/00": "0",
    "1/2/00": "2",
    "1/1/00": "1",
    "1/3/00": "3",
    "1/4/00": "4",
    "1/5/00": "5"}

df['number_of_open_complaints'] = df['number_of_open_complaints'].replace(complaints_)

In [13]:
df["number_of_open_complaints"] = pd.to_numeric(df["number_of_open_complaints"], errors='coerce')

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12074 entries, 0 to 12073
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   customer                   9137 non-null   object
 1   state                      9137 non-null   object
 2   gender                     9015 non-null   object
 3   education                  9137 non-null   object
 4   customer_lifetime_value    9130 non-null   float64
 5   income                     9137 non-null   float64
 6   monthly_premium_auto       9137 non-null   float64
 7   number_of_open_complaints  9137 non-null   float64
 8   policy_type                9137 non-null   object
 9   vehicle_class              9137 non-null   object
 10  total_claim_amount         9137 non-null   float64
dtypes: float64(5), object(6)
memory usage: 1.0+ MB

In [15]:
df.isnull().sum()

customer                     2937
state                        2937
gender                       3059
education                    2937
customer_lifetime_value      2944
income                       2937
monthly_premium_auto         2937
number_of_open_complaints    2937
policy_type                  2937
vehicle_class                2937
total_claim_amount           2937
dtype: int64

In [16]:
df.dropna(how='all', inplace=True)

In [17]:
df.isnull().sum()

customer                       0
state                          0
gender                       122
education                      0
customer_lifetime_value        7
income                         0
monthly_premium_auto           0
number_of_open_complaints      0
policy_type                    0
vehicle_class                  0
total_claim_amount             0
dtype: int64

In [18]:
df['gender'] = df['gender'].fillna('unknown')
df.head()

,customer,state,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount
0,RB50392,Washington,unknown,Master,NaN,0.0,1000.0,0.0,Personal Auto,Four-Door Car,2.704934
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,0.0,Personal Auto,Four-Door Car,1131.464935
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,0.0,Personal Auto,Two-Door Car,566.472247
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,0.0,Corporate Auto,SUV,529.881344
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,0.0,Personal Auto,Four-Door Car,17.269323

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [19]:
# Your code goes here

df4 = pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv")
df4.head()

,unnamed:_0,customer,state,customer_lifetime_value,response,coverage,education,effective_to_date,employmentstatus,gender,...,number_of_policies,policy_type,policy,renew_offer_type,sales_channel,total_claim_amount,vehicle_class,vehicle_size,vehicle_type,month
0,0,DK49336,Arizona,4809.216960,No,Basic,College,2011-02-18,Employed,M,...,9,Corporate Auto,Corporate L3,Offer3,Agent,292.800000,Four-Door Car,Medsize,A,2
1,1,KX64629,California,2228.525238,No,Basic,College,2011-01-18,Unemployed,F,...,1,Personal Auto,Personal L3,Offer4,Call Center,744.924331,Four-Door Car,Medsize,A,1
2,2,LZ68649,Washington,14947.917300,No,Basic,Bachelor,2011-02-10,Employed,M,...,2,Personal Auto,Personal L3,Offer3,Call Center,480.000000,SUV,Medsize,A,2
3,3,XL78013,Oregon,22332.439460,Yes,Extended,College,2011-01-11,Employed,M,...,2,Corporate Auto,Corporate L3,Offer2,Branch,484.013411,Four-Door Car,Medsize,A,1
4,4,QA50777,Oregon,9025.067525,No,Premium,Bachelor,2011-01-17,Medical Leave,F,...,7,Personal Auto,Personal L2,Offer1,Branch,707.925645,Four-Door Car,Medsize,A,1

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [20]:
print(f"  → Rows: {df4.shape[0]:,}  |  Columns: {df4.shape[1]}")
print()

  → Rows: 10,910  |  Columns: 27

In [21]:
print(f"  → unique channels in 'sales_channel': {df4['sales_channel'].unique().tolist()}")
print(f"  → type of 'total_claim_amount': {df4['total_claim_amount'].dtype}")
print(f"  → null values in 'total_claim_amount': {df4['total_claim_amount'].isnull().sum()}")
print()

  → unique channels in 'sales_channel': ['Agent', 'Call Center', 'Branch', 'Web']
  → type of 'total_claim_amount': float64
  → null values in 'total_claim_amount': 0

In [22]:
pivot = pd.pivot_table(
    data=df4,
    values="total_claim_amount",  
    index="sales_channel",         
    aggfunc="sum",                 
)

In [23]:
pivot = pivot.round(2)
pivot.columns = ["Total Revenue"]

In [24]:
pivot = pivot.sort_values("Total Revenue", ascending=False)
print(pivot)

               Total Revenue
sales_channel
Agent             1810226.82
Branch            1301204.00
Call Center        926600.82
Web                706600.04

In [25]:
total_global = pivot["Total Revenue"].sum()
pivot["% from total"] = ((pivot["Total Revenue"] / total_global) * 100).round(2)

In [26]:
print(pivot.to_string())
print()

               Total Revenue  % from total
sales_channel
Agent             1810226.82         38.15
Branch            1301204.00         27.42
Call Center        926600.82         19.53
Web                706600.04         14.89

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [27]:
pivot2 = pd.pivot_table(
    data=df4,
    values="customer_lifetime_value",
    index="education",            
    columns="gender",             
    aggfunc="mean",               
)

In [28]:
pivot2 = pivot2.round(2)
 
print(pivot2.to_string())
print()

gender                      F        M
education
Bachelor              7874.27  7703.60
College               7748.82  8052.46
Doctor                7328.51  7415.33
High School or Below  8675.22  8149.69
Master                8157.05  8168.83

In [30]:
pivot2["Mean"] = pivot2.mean(axis=1).round(2)
pivot2 = pivot2.sort_values("Mean", ascending=False)
print(pivot2.to_string())
print()

gender                      F        M     Mean
education
High School or Below  8675.22  8149.69  8412.46
Master                8157.05  8168.83  8162.94
College               7748.82  8052.46  7900.64
Bachelor              7874.27  7703.60  7788.94
Doctor                7328.51  7415.33  7371.92

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [36]:
print(f"  → Policy types:  {df4['policy_type'].unique().tolist()}")
print(f"  → Months:        {sorted(df4['month'].unique().tolist())}")
print(f"  → Complaints (unique values sample): {df4['number_of_open_complaints'].unique()}")
print()

  → Policy types:  ['Corporate Auto', 'Personal Auto', 'Special Auto']
  → Months:        [1, 2]
  → Complaints (unique values sample): [0.         0.38425611 3.         1.         2.         4.
 5.        ]

In [38]:
pivot_wide = pd.pivot_table(
    data=df4,
    values="number_of_open_complaints",
    index="policy_type",
    columns="month",
    aggfunc="sum",
    fill_value=0,
)

In [39]:
print(pivot_wide)
print()

month                     1            2
policy_type
Corporate Auto   443.434952   385.208135
Personal Auto   1727.605722  1453.684441
Special Auto      87.074049    95.226817