# Lab | Data Structuring and Combining Data

## Challenge 1: Combining & Cleaning Data

In this challenge, we will be working with the customer data from an insurance company, as we did in the two previous labs. The data can be found here:
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv

But this time, we got new data, which can be found in the following 2 CSV files located at the links below.

- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv
- https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv

Note that you'll need to clean and format the new data.

Observation:
- One option is to first combine the three datasets and then apply the cleaning function to the new combined dataset
- Another option would be to read the clean file you saved in the previous lab, and just clean the two new files and concatenate the three clean datasets

In [2]:
import pandas as pd
import numpy as np

In [4]:
df1= pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file1.csv")
df2= pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file2.csv")
df3= pd.read_csv("https://raw.githubusercontent.com/data-bootcamp-v4/data/main/file3.csv")

In [5]:
df = (pd.concat([df1, df2, df3], axis=0))

def df_info(df):
    print("\n    ---- df info ---")
    print(df.info())
    print("\n    ---- Empty Values ---")
    print(df.isna().sum())
    print("\n    ----- Dtypes -----")
    print(df.dtypes)
    print("\n    ---- Statistics ---")
    return df.describe()
df_info(df)

    ---- df info ---
<class 'pandas.core.frame.DataFrame'>
Index: 12074 entries, 0 to 7069
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Customer                   9137 non-null   object
 1   ST                         2067 non-null   object
 2   GENDER                     1945 non-null   object
 3   Education                  9137 non-null   object
 4   Customer Lifetime Value    9130 non-null   object
 5   Income                     9137 non-null   float64
 6   Monthly Premium Auto       9137 non-null   float64
 7   Number of Open Complaints  9137 non-null   object
 8   Policy Type                9137 non-null   object
 9   Vehicle Class              9137 non-null   object
 10  Total Claim Amount         9137 non-null   float64
 11  State                      7070 non-null   object
 12  Gender                     7070 non-null   object
dtypes: float64(3), object(10)
memory usage: 1.3+ MB
None

    ---- Empty Values ---
Customer                      2937
ST                           10007
GENDER                       10129
Education                     2937
Customer Lifetime Value       2944
Income                        2937
Monthly Premium Auto          2937
Number of Open Complaints     2937
Policy Type                   2937
Vehicle Class                 2937
Total Claim Amount            2937
State                         5004
Gender                        5004
dtype: int64

    ----- Dtypes -----
Customer                      object
ST                            object
GENDER                        object
Education                     object
Customer Lifetime Value       object
Income                       float64
Monthly Premium Auto         float64
Number of Open Complaints     object
Policy Type                   object
Vehicle Class                 object
Total Claim Amount           float64
State                         object
Gender                        object
dtype: object

    ---- Statistics ---

             Income  Monthly Premium Auto  Total Claim Amount
count   9137.000000           9137.000000         9137.000000
mean   37828.820291            110.391266          430.527140
std    30358.716159            581.376032          289.582968
min        0.000000             61.000000            0.099007
25%        0.000000             68.000000          266.996814
50%    34244.000000             83.000000          377.561463
75%    62447.000000            109.000000          546.420009
max    99981.000000          35354.000000         2893.239678

In [6]:
df0 = df.copy()
df0.head(3)

,Customer,ST,GENDER,Education,Customer Lifetime Value,Income,Monthly Premium Auto,Number of Open Complaints,Policy Type,Vehicle Class,Total Claim Amount,State,Gender
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934,NaN,NaN
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935,NaN,NaN
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247,NaN,NaN

In [7]:
def rename_columns(df0):
    df0.rename(columns={col : col.strip() for col in df0.columns}, inplace = True)
    df0.rename(columns={col : col.replace(" ", "_").lower() for col in df0.columns}, inplace = True)
    return df0

In [8]:
df0 = rename_columns(df0)
df0.head()

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,state,gender
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934,NaN,NaN
1,QZ44356,Arizona,F,Bachelor,697953.59%,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935,NaN,NaN
2,AI49188,Nevada,F,Bachelor,1288743.17%,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247,NaN,NaN
3,WW63253,California,M,Bachelor,764586.18%,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344,NaN,NaN
4,GA49547,Washington,M,High School or Below,536307.65%,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323,NaN,NaN

In [9]:
df0["customer_lifetime_value"] = df0["customer_lifetime_value"].apply(lambda x: float(str(x).replace('%', '')) if pd.notnull(x) else x)

df0.head()

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,state,gender
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934,NaN,NaN
1,QZ44356,Arizona,F,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935,NaN,NaN
2,AI49188,Nevada,F,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247,NaN,NaN
3,WW63253,California,M,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344,NaN,NaN
4,GA49547,Washington,M,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323,NaN,NaN

In [10]:
def convert_to_numeric(df0, cols):
    for col in cols:
        if col in df0.columns:
            df0[col] = pd.to_numeric(df0[col], errors='coerce')
    return df0

In [11]:
df0 = convert_to_numeric(df0, ["customer_lifetime_value", "income", "monthly_premium_auto"])
df0.dtypes

customer                      object
st                            object
gender                        object
education                     object
customer_lifetime_value      float64
income                       float64
monthly_premium_auto         float64
number_of_open_complaints     object
policy_type                   object
vehicle_class                 object
total_claim_amount           float64
state                         object
gender                        object
dtype: object

In [18]:
replacements = {
        'gender':        {'M': 'male', 'Male': 'male', 'F': 'female', 'Femal': 'female'},
        'st':         {'AZ': 'Arizona', 'Cali': 'California', 'WA': 'Washington'},
        'education':     {'Bachelors': 'Bachelor'},
        'vehicle_class': {'Sports Car': 'Luxury', 'Luxury SUV': 'Luxury', 'Luxury Car': 'Luxury'}
    }
    

def clean_vals(df0, replacements):
    for col, mapping in replacements.items():
        if col in df0.columns:
            df0[col] = df0[col].replace(mapping)
    return df0

In [19]:
df0 = clean_vals (df0, replacements)
df0.head()

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,state,gender
0,RB50392,Washington,NaN,Master,NaN,0.0,1000.0,1/0/00,Personal Auto,Four-Door Car,2.704934,NaN,NaN
1,QZ44356,Arizona,female,Bachelor,697953.59,0.0,94.0,1/0/00,Personal Auto,Four-Door Car,1131.464935,NaN,NaN
2,AI49188,Nevada,female,Bachelor,1288743.17,48767.0,108.0,1/0/00,Personal Auto,Two-Door Car,566.472247,NaN,NaN
3,WW63253,California,male,Bachelor,764586.18,0.0,106.0,1/0/00,Corporate Auto,SUV,529.881344,NaN,NaN
4,GA49547,Washington,male,High School or Below,536307.65,36357.0,68.0,1/0/00,Personal Auto,Four-Door Car,17.269323,NaN,NaN

In [23]:
df0['st'].unique()

array(['Washington', 'Arizona', 'Nevada', 'California', 'Oregon', nan],
      dtype=object)

In [27]:
df0['gender'].unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [36]:
def clean_na(df0):
   
    df0['gender'] = df0['gender'].fillna('unknown')
    return df0

In [37]:
df0 = clean_na(df0)
df0.head(3)

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,state,gender
0,RB50392,Washington,unknown,Master,NaN,0.0,1000.0,1,Personal Auto,Four-Door Car,2.704934,NaN,unknown
1,QZ44356,Arizona,female,Bachelor,697953.59,0.0,94.0,1,Personal Auto,Four-Door Car,1131.464935,NaN,unknown
2,AI49188,Nevada,female,Bachelor,1288743.17,48767.0,108.0,1,Personal Auto,Two-Door Car,566.472247,NaN,unknown

In [38]:
clean_df = df0

In [39]:
clean_df["number_of_open_complaints"] = clean_df ["number_of_open_complaints"].str[0]
clean_df['gender'] = clean_df['gender'].fillna("unknown")
clean_df.head()

,customer,st,gender,education,customer_lifetime_value,income,monthly_premium_auto,number_of_open_complaints,policy_type,vehicle_class,total_claim_amount,state,gender
0,RB50392,Washington,unknown,Master,NaN,0.0,1000.0,1,Personal Auto,Four-Door Car,2.704934,NaN,unknown
1,QZ44356,Arizona,female,Bachelor,697953.59,0.0,94.0,1,Personal Auto,Four-Door Car,1131.464935,NaN,unknown
2,AI49188,Nevada,female,Bachelor,1288743.17,48767.0,108.0,1,Personal Auto,Two-Door Car,566.472247,NaN,unknown
3,WW63253,California,male,Bachelor,764586.18,0.0,106.0,1,Corporate Auto,SUV,529.881344,NaN,unknown
4,GA49547,Washington,male,High School or Below,536307.65,36357.0,68.0,1,Personal Auto,Four-Door Car,17.269323,NaN,unknown

# Challenge 2: Structuring Data

In this challenge, we will continue to work with customer data from an insurance company, but we will use a dataset with more columns, called marketing_customer_analysis.csv, which can be found at the following link:

https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv

This dataset contains information such as customer demographics, policy details, vehicle information, and the customer's response to the last marketing campaign. Our goal is to explore and analyze this data by performing data cleaning, formatting, and structuring.

In [9]:
df2 = pd.read_csv('https://raw.githubusercontent.com/data-bootcamp-v4/data/main/marketing_customer_analysis_clean.csv')
display (df2.nunique())
print("\n shape")
print(df2.shape)

print("\ndtypes")
print(df2.dtypes)

unnamed:_0                       10910
customer                          9134
state                                5
customer_lifetime_value           8041
response                             2
coverage                             3
education                            5
effective_to_date                   59
employmentstatus                     5
gender                               2
income                            5694
location_code                        3
marital_status                       3
monthly_premium_auto               202
months_since_last_claim             37
months_since_policy_inception      100
number_of_open_complaints            7
number_of_policies                   9
policy_type                          3
policy                               9
renew_offer_type                     4
sales_channel                        4
total_claim_amount                5106
vehicle_class                        6
vehicle_size                         3
vehicle_type                         1
month                                2
dtype: int64

 shape
(10910, 27)

dtypes
unnamed:_0                         int64
customer                          object
state                             object
customer_lifetime_value          float64
response                          object
coverage                          object
education                         object
effective_to_date                 object
employmentstatus                  object
gender                            object
income                             int64
location_code                     object
marital_status                    object
monthly_premium_auto               int64
months_since_last_claim          float64
months_since_policy_inception      int64
number_of_open_complaints        float64
number_of_policies                 int64
policy_type                       object
policy                            object
renew_offer_type                  object
sales_channel                     object
total_claim_amount               float64
vehicle_class                     object
vehicle_size                      object
vehicle_type                      object
month                              int64
dtype: object

In [12]:
df2.drop_duplicates(subset=['customer'], inplace=True)

1. You work at the marketing department and you want to know which sales channel brought the most sales in terms of total revenue. Using pivot, create a summary table showing the total revenue for each sales channel (branch, call center, web, and mail).
Round the total revenue to 2 decimal points.  Analyze the resulting table to draw insights.

In [14]:
pivot = df2.pivot_table(
    columns='sales_channel', 
    values='customer_lifetime_value', 
    aggfunc='sum'
).style.format("{:,.2f}") 

display(pivot)

2. Create a pivot table that shows the average customer lifetime value per gender and education level. Analyze the resulting table to draw insights.

In [16]:
df2.pivot_table ( values = ['customer_lifetime_value'], columns='gender', index='education', aggfunc = 'mean').style.format ("{:,.2f}")

## Bonus

You work at the customer service department and you want to know which months had the highest number of complaints by policy type category. Create a summary table showing the number of complaints by policy type and month.
Show it in a long format table.

*In data analysis, a long format table is a way of structuring data in which each observation or measurement is stored in a separate row of the table. The key characteristic of a long format table is that each column represents a single variable, and each row represents a single observation of that variable.*

*More information about long and wide format tables here: https://www.statology.org/long-vs-wide-data/*

In [19]:
pivot_wide = pd.pivot_table( data=df2, values='number_of_open_complaints', index='policy_type', columns='month', aggfunc='sum', fill_value=0)
print(pivot_wide)

month                     1            2
policy_type
Corporate Auto   372.296195   340.527683
Personal Auto   1464.342220  1186.194123
Special Auto      76.768512    71.152768